package hbm;
// Generated 9/02/2020 11:15:53 AM by Hibernate Tools 3.5.0.Final

/**
 * Products generated by hbm2java
 */
public class Products implements java.io.Serializable {

	private int idItem;
	private String nombre;
	private Long cantidad;
	private String codigoInv;

	public Products() {
	}

	public Products(int idItem) {
		this.idItem = idItem;
	}

	public Products(int idItem, String nombre, Long cantidad, String codigoInv) {
		this.idItem = idItem;
		this.nombre = nombre;
		this.cantidad = cantidad;
		this.codigoInv = codigoInv;
	}

	public int getIdItem() {
		return this.idItem;
	}

	public void setIdItem(int idItem) {
		this.idItem = idItem;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Long getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Long cantidad) {
		this.cantidad = cantidad;
	}

	public String getCodigoInv() {
		return this.codigoInv;
	}

	public void setCodigoInv(String codigoInv) {
		this.codigoInv = codigoInv;
	}

}
